### ISSUE TITLE
Remixer should fail-fast if Application is not implemented

### ISSUE THREAD

**Issue by pingpongboss** [material-foundation/material-remixer-android#88]
Context: http://codereview.cc/D1976#40068

I tried integrating Remixer from memory, and I didn't subclass Application correct (to call the remixer initialization code). This should fail-fast so the user knows they forgot to do something. For example, I just realized that my previous integration with `rebound` has the same issue. I did [subclass application](https://github.com/material-motion/family-rebound-android/blob/develop/sample/src/main/java/com/google/android/material/motion/family/rebound/sample/ReboundApplication.java) but I did not add it to my [AndroidManifest](https://github.com/material-motion/family-rebound-android/blob/develop/sample/src/main/AndroidManifest.xml#L20). I would have never known this would be a problem.

**Comment by pingpongboss** [comment]
Here's the current exception that's thrown
```
12-15 21:07:09.245 6276-6276/com.google.android.material.motion.family.rebound.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                        Process: com.google.android.material.motion.family.rebound.sample, PID: 6276
                                                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.material.motion.family.rebound.sample/com.google.android.material.motion.family.rebound.sample.MainActivity}: java.lang.IllegalArgumentException: dataType cannot be unset for RemixerItem
                                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                                                         Caused by: java.lang.IllegalArgumentException: dataType cannot be unset for RemixerItem
                                                                                                            at com.google.android.libraries.remixer.RemixerItem$Builder.checkBaseFields(RemixerItem.java:150)
                                                                                                            at com.google.android.libraries.remixer.RangeVariable$Builder.build(RangeVariable.java:206)
                                                                                                            at com.google.android.material.motion.family.rebound.sample.MainActivity_RemixerBinder.bindInstance(MainActivity_RemixerBinder.java:29)
                                                                                                            at com.google.android.material.motion.family.rebound.sample.MainActivity_RemixerBinder.bindInstance(MainActivity_RemixerBinder.java:13)
                                                                                                            at com.google.android.libraries.remixer.annotation.RemixerBinder.bind(RemixerBinder.java:37)
                                                                                                            at com.google.android.material.motion.family.rebound.sample.MainActivity.onCreate(MainActivity.java:59)
                                                                                                            at android.app.Activity.performCreate(Activity.java:6679)
                                                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                            at android.os.Looper.loop(Looper.java:154) 
                                                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

It's super confusing. Please throw an exception that reminds the client to implement Application correctly!
